### ISSUE TITLE
Words with hyphens

### ISSUE THREAD

**Issue by simonewebdesign** [bitwalker/combine#26]
Hi, first of all thanks for the great library :)

I was trying to parse simple hyphenated words but apparently [word](https://github.com/bitwalker/combine/blob/master/lib/combine/parsers/text.ex#L452) is not the right choice. Example:

``` elixir
Interactive Elixir (1.3.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> use Combine
Combine.Parsers.Binary
iex(2)> Combine.parse("foo-bar", word)
["foo"]  # I was expecting ["foo-bar"]
```

Is this intentional?

**Comment by bitwalker** [comment]
A word in Combine parlance is anything alphanumeric plus underscores. I would rather not change that to include hyphens as it would likely break pre-existing parsers, and the terminology is derived from regular expressions anyway (which is why it uses a regex on the backend). I would recommend using `word_of` with your own regex defining what words mean in your grammar.

**Comment by simonewebdesign** [comment]
Yes, that's what I did:

```elixir
iex> Combine.parse("foo-bar", word_of(~r/[\w-]+/))
["foo-bar"]
```

Not as pretty as `word`, but it does the job. Thanks. :)

**Comment by bitwalker** [comment]
No problem :), sorry for the delay!
