### ISSUE TITLE
How to do handle failure in 'optional' parsing

### ISSUE THREAD

**Issue by tdejager** [bitwalker/combine#38]
Hi!

I don't know if this is the right place to be asking this question, so if it needs to be moved somewhere else let me know.

My question is regarding the parsing of the following format:

```bash
#Can be either
node (x, y) -> node (x, y)
# or (x, y) are optional
node -> node
```

I have some rules set up, the most important being:

```elixir
defp node_parser(prev \\ nil) do
    prev
    |> label(word(), "name")
    |> skip(spaces())
    |> position_parser()
  end

  defp position_parser(previous) do
    previous
    |> option(
        ignore(char("("))
        |> int_parser("x")
        |> ignore(char(","))
        |> skip(spaces())
        |> int_parser("y")
        |> ignore(char(")")))
  end

  defp relation_parser(prev) do
    prev
    |> skip(spaces())
    |> option(ignore(string("->")) |> skip(spaces) |> node_parser())
  end

  defp int_parser(prev, name) when is_binary(name) do
    prev
    |> label(integer, name)
  end
```

When parsing the desired output this works:
```elixir
iex(1)> Parser.parser("foo (175, 164) -> bar (100, 0)")
["foo", 175, 164, "bar", 100, 0]
```

However when making an error:

```elixir
iex(8)> Parser.parser("foo (175, ) -> bar (100, 0)")
["foo", nil, nil]
```

Which is caused by the failing optional, what would be the best way to parse such a sequence? And failing when it encounters an erroneous situation like the above? 

I know that with the default mechanics the parsing returns a nil when failing and that this is caught by the optional. However, I am wondering if a workaround would be available?

Cheers :)

**Comment by bitwalker** [comment]
I think some of your example code is missing, since I can't see the definition of `Parser.parse` - in any case, if you need parsing to fail, then you should use `choice` and define the different branches, this way parsing will fail as you expect. `option` isn't a good fit for capturing the reason why the inner parser failed and doing something based on that. If you want something like `option` but with more control, then you can define your own parsers via `defparser`.

Hope that helps!
