### ISSUE TITLE
should `satisfy` reset line/col on failure?

### ISSUE THREAD

**Issue by sasa1977** [bitwalker/combine#8]
I'm trying to apply custom error on `satisfy` parser by using `satisfy(...) |> label(...)`. This basically works, but the reported column number is not correct. 

If a predicate fails the parser state is at the position after the failed term, since the term has been properly matched by the inner parser. The lineno/col is properly included in the generated error, but if I want to customize error using `label`, then the new parser state will be used, and thus contain a wrong error number.

As far as I can tell, a proper fix would be to reset `line` and `column` to initial values [here](https://github.com/bitwalker/combine/blob/master/lib/combine/parsers/base.ex#L520). I tried it locally and it works.

I can prepare the pull if you agree, but wanted to check first if you agree this is the proper way to go? I'm fairly new to combinators, so I might be missing something here.

**Comment by bitwalker** [comment]
@You are correct, it should reset on failure. If you can open a PR, I'll get that merged. 

I have another bug I found today, a bigger one, which I've fixed, but am doing testing locally - the `sequence` combinator (well, really the `pipe` combinator, which `sequence` uses) was fundamentally broken, given a parser like: `sequence([date, ignore(char("T")), time])`, and a string `2014-07-22T12:30:05.0002Z`, the result would be something like `[2014, 7, 12, 30, 5.0002, {22, "UTC"}]`, when it should be `[[2014, 7, 22, 12, 30, 5.0002, "UTC"]]`. Anyway, since you are working with combine right now, figured you might want a heads up on that one, I'll be pushing a fix today.

EDIT: Fixed the correct output.

**Comment by bitwalker** [comment]
I've pushed a fix to master for the issue I mentioned above, just FYI
